/**
 * Full Scan Stock Universe
 * Three segments: Large Cap, Mid Cap, Small Cap
 * Each entry: { symbol, name, yahooSymbol? }
 * Default Yahoo ticker = symbol + '.NS'
 */

import type { StockEntry } from './stock-universe'

// ─── Large Cap ─────────────────────────────────────────────────────────────────
// NIFTY 100 + additional large-cap NSE stocks (~150 total)

export const LARGE_CAP_EXTRA: StockEntry[] = [
  { symbol: 'PIDILITIND',    name: 'Pidilite Industries' },
  { symbol: 'ABB',           name: 'ABB India' },
  { symbol: 'CONCOR',        name: 'Container Corp of India' },
  { symbol: 'CUMMINSIND',    name: 'Cummins India' },
  { symbol: 'TATACHEM',      name: 'Tata Chemicals' },
  { symbol: 'UPL',           name: 'UPL' },
  { symbol: 'BALKRISIND',    name: 'Balkrishna Industries' },
  { symbol: 'TATAELXSI',     name: 'Tata Elxsi' },
  { symbol: 'DIXON',         name: 'Dixon Technologies' },
  { symbol: 'KPITTECH',      name: 'KPIT Technologies' },
  { symbol: 'MPHASIS',       name: 'Mphasis' },
  { symbol: 'COFORGE',       name: 'Coforge' },
  { symbol: 'DEEPAKNTR',     name: 'Deepak Nitrite' },
  { symbol: 'FLUOROCHEM',    name: 'Gujarat Fluorochemicals' },
  { symbol: 'ESCORTSKUBOTA', name: 'Escorts Kubota' },
  { symbol: 'EXIDEIND',      name: 'Exide Industries' },
  { symbol: 'INTERGLOBE',    name: 'InterGlobe Aviation (IndiGo)' },
  { symbol: 'JKCEMENT',      name: 'JK Cement' },
  { symbol: 'ABCAPITAL',     name: 'Aditya Birla Capital' },
  { symbol: 'MFSL',          name: 'Max Financial Services' },
  { symbol: 'LICI',          name: 'Life Insurance Corp of India' },
  { symbol: 'STARHEALTH',    name: 'Star Health Insurance' },
  { symbol: 'ICICIGI',       name: 'ICICI Lombard General Insurance' },
  { symbol: 'ASTRAL',        name: 'Astral' },
  { symbol: 'APLAPOLLO',     name: 'APL Apollo Tubes' },
  { symbol: 'DALBHARAT',     name: 'Dalmia Bharat' },
  { symbol: 'CROMPTON',      name: 'Crompton Greaves Consumer' },
  { symbol: 'BATAINDIA',     name: 'Bata India' },
  { symbol: 'KAJARIACER',    name: 'Kajaria Ceramics' },
  { symbol: 'INDIAMART',     name: 'IndiaMart InterMesh' },
  { symbol: 'JUBLFOOD',      name: 'Jubilant FoodWorks' },
  { symbol: 'IGL',           name: 'Indraprastha Gas' },
  { symbol: 'ABBOTINDIA',    name: 'Abbott India' },
  { symbol: 'FEDERALBNK',    name: 'Federal Bank' },
  { symbol: 'SBICARD',       name: 'SBI Cards & Payment Services' },
  { symbol: 'APOLLOTYRE',    name: 'Apollo Tyres' },
  { symbol: 'ASHOKLEY',      name: 'Ashok Leyland' },
  { symbol: 'BIOCON',        name: 'Biocon' },
  { symbol: 'GLENMARK',      name: 'Glenmark Pharmaceuticals' },
  { symbol: 'LAURUSLABS',    name: 'Laurus Labs' },
  { symbol: 'BSOFT',         name: 'Birlasoft' },
  { symbol: 'DELHIVERY',     name: 'Delhivery' },
  { symbol: 'POLICYBZR',     name: 'PB Fintech (PolicyBazaar)' },
  { symbol: 'HONASA',        name: 'Honasa Consumer (Mamaearth)' },
  { symbol: 'RAMCOCEM',      name: 'Ramco Cements' },
  { symbol: 'JSWENERGY',     name: 'JSW Energy' },
  { symbol: 'AJANTPHARM',    name: 'Ajanta Pharma' },
  { symbol: 'IPCALAB',       name: 'Ipca Laboratories' },
  { symbol: 'LINDEINDIA',    name: 'Linde India' },
  { symbol: 'BLUEDART',      name: 'Blue Dart Express' },
]

// ─── Mid Cap ───────────────────────────────────────────────────────────────────

export const MID_CAP_STOCKS: StockEntry[] = [
  { symbol: 'AAVAS',        name: 'Aavas Financiers' },
  { symbol: 'ABFRL',        name: 'Aditya Birla Fashion & Retail' },
  { symbol: 'AIAENG',       name: 'AIA Engineering' },
  { symbol: 'AKZOINDIA',    name: 'Akzo Nobel India' },
  { symbol: 'AUBANKIND',    name: 'AU Small Finance Bank' },
  { symbol: 'BAJAJHLDNG',   name: 'Bajaj Holdings & Investment' },
  { symbol: 'BIRLACORP',    name: 'Birla Corporation' },
  { symbol: 'BLUESTARCO',   name: 'Blue Star' },
  { symbol: 'BRIGADE',      name: 'Brigade Enterprises' },
  { symbol: 'CAMPUS',       name: 'Campus Activewear' },
  { symbol: 'CESC',         name: 'CESC' },
  { symbol: 'CGPOWER',      name: 'CG Power & Industrial' },
  { symbol: 'CYIENT',       name: 'Cyient' },
  { symbol: 'DELTACORP',    name: 'Delta Corp' },
  { symbol: 'DHANUKA',      name: 'Dhanuka Agritech' },
  { symbol: 'EMAMILTD',     name: 'Emami' },
  { symbol: 'EQUITASBNK',   name: 'Equitas Small Finance Bank' },
  { symbol: 'FINEORG',      name: 'Fine Organic Industries' },
  { symbol: 'FORTIS',       name: 'Fortis Healthcare' },
  { symbol: 'GALAXYSURF',   name: 'Galaxy Surfactants' },
  { symbol: 'GNFC',         name: 'GNFC' },
  { symbol: 'GODREJIND',    name: 'Godrej Industries' },
  { symbol: 'GRANULES',     name: 'Granules India' },
  { symbol: 'GSFC',         name: 'Gujarat State Fertilizers' },
  { symbol: 'HFCL',         name: 'HFCL' },
  { symbol: 'HINDCOPPER',   name: 'Hindustan Copper' },
  { symbol: 'JYOTHY',       name: 'Jyothy Labs' },
  { symbol: 'KALYANKJIL',   name: 'Kalyan Jewellers' },
  { symbol: 'KRBL',         name: 'KRBL' },
  { symbol: 'LEMONTREE',    name: 'Lemon Tree Hotels' },
  { symbol: 'MARKSANS',     name: 'Marksans Pharma' },
  { symbol: 'MASTEK',       name: 'Mastek' },
  { symbol: 'MCX',          name: 'Multi Commodity Exchange' },
  { symbol: 'METROPOLIS',   name: 'Metropolis Healthcare' },
  { symbol: 'NATCOPHARM',   name: 'Natco Pharma' },
  { symbol: 'NAVIN',        name: 'Navin Fluorine International' },
  { symbol: 'NBCC',         name: 'NBCC India' },
  { symbol: 'NIACL',        name: 'New India Assurance' },
  { symbol: 'RAYMOND',      name: 'Raymond' },
  { symbol: 'RITES',        name: 'RITES' },
  { symbol: 'SCI',          name: 'Shipping Corporation of India' },
  { symbol: 'SOBHA',        name: 'Sobha' },
  { symbol: 'SUPRAJIT',     name: 'Suprajit Engineering' },
  { symbol: 'TEAMLEASE',    name: 'TeamLease Services' },
  { symbol: 'UJJIVAN',      name: 'Ujjivan Financial Services' },
  { symbol: 'VGUARD',       name: 'V-Guard Industries' },
  { symbol: 'WESTLIFE',     name: 'Westlife Foodworld' },
  { symbol: 'WHIRLPOOL',    name: 'Whirlpool of India' },
  { symbol: 'ALEMBICLTD',   name: 'Alembic Pharmaceuticals' },
  { symbol: 'AMARAJABAT',   name: 'Amara Raja Energy & Mobility' },
  { symbol: 'ATUL',         name: 'Atul' },
  { symbol: 'AVANTIFEED',   name: 'Avanti Feeds' },
  { symbol: 'CARBORUNDUM',  name: 'Carborundum Universal' },
  { symbol: 'CASTROLIND',   name: 'Castrol India' },
  { symbol: 'CENTURYPLY',   name: 'Century Plyboards' },
  { symbol: 'CHAMBLFERT',   name: 'Chambal Fertilisers' },
  { symbol: 'ECLERX',       name: 'eClerx Services' },
  { symbol: 'ELGIEQUIP',    name: 'Elgi Equipments' },
  { symbol: 'ENGINERSIN',   name: 'Engineers India' },
  { symbol: 'EPIGRAL',      name: 'Epigral' },
  { symbol: 'GRAPHITE',     name: 'Graphite India' },
  { symbol: 'GRINDWELL',    name: 'Grindwell Norton' },
  { symbol: 'GUJGASLTD',    name: 'Gujarat Gas' },
  { symbol: 'HATSUN',       name: 'Hatsun Agro' },
  { symbol: 'HAWKINCOOK',   name: 'Hawkins Cookers' },
  { symbol: 'HIKAL',        name: 'Hikal' },
  { symbol: 'HUDCO',        name: 'HUDCO' },
  { symbol: 'INOXWIND',     name: 'Inox Wind' },
  { symbol: 'JAMNAAUTO',    name: 'Jamna Auto Industries' },
  { symbol: 'JINDALSAW',    name: 'Jindal Saw' },
  { symbol: 'JKPAPER',      name: 'JK Paper' },
  { symbol: 'KANSAINER',    name: 'Kansai Nerolac Paints' },
  { symbol: 'KOLTEPATIL',   name: 'Kolte-Patil Developers' },
  { symbol: 'KPRMILL',      name: 'KPR Mill' },
  { symbol: 'MANAPPURAM',   name: 'Manappuram Finance' },
  { symbol: 'NCC',          name: 'NCC' },
  { symbol: 'NILKAMAL',     name: 'Nilkamal' },
  { symbol: 'ORIENTELEC',   name: 'Orient Electric' },
  { symbol: 'PNBHOUSING',   name: 'PNB Housing Finance' },
  { symbol: 'PVR',          name: 'PVR INOX' },
  { symbol: 'RELAXO',       name: 'Relaxo Footwears' },
  { symbol: 'SAFARI',       name: 'Safari Industries' },
  { symbol: 'SAPPHIRE',     name: 'Sapphire Foods India' },
  { symbol: 'SCHAEFFLER',   name: 'Schaeffler India' },
  { symbol: 'SEQUENT',      name: 'SeQuent Scientific' },
  { symbol: 'STARCEMENT',   name: 'Star Cement' },
  { symbol: 'SUNTV',        name: 'Sun TV Network' },
  { symbol: 'TATACHEM',     name: 'Tata Chemicals' },  // also in large cap extra
  { symbol: 'TIINDIA',      name: 'Tube Investments of India' },
  { symbol: 'TTMLTD',       name: 'Tata Teleservices (Maharashtra)' },
  { symbol: 'UJJIVANSFB',   name: 'Ujjivan Small Finance Bank' },
  { symbol: 'VINDHYATEL',   name: 'Vindhya Telelinks' },
  { symbol: 'ZENSARTECH',   name: 'Zensar Technologies' },
]

// ─── Small Cap ─────────────────────────────────────────────────────────────────

export const SMALL_CAP_STOCKS: StockEntry[] = [
  { symbol: 'AARTIIND',     name: 'Aarti Industries' },
  { symbol: 'AETHER',       name: 'Aether Industries' },
  { symbol: 'AJMERA',       name: 'Ajmera Realty & Infra' },
  { symbol: 'ANDHRSUGAR',   name: 'Andhra Sugars' },
  { symbol: 'APCOTEXIND',   name: 'Apcotex Industries' },
  { symbol: 'ARVINDFASHN',  name: 'Arvind Fashions' },
  { symbol: 'ASTERDM',      name: 'Aster DM Healthcare' },
  { symbol: 'ATGL',         name: 'Adani Total Gas' },
  { symbol: 'BALAMINES',    name: 'Balaji Amines' },
  { symbol: 'BBTC',         name: 'Bombay Burmah Trading' },
  { symbol: 'BDL',          name: 'Bharat Dynamics' },
  { symbol: 'BEML',         name: 'BEML' },
  { symbol: 'BORNOMIN',     name: 'Borosil Renewables' },
  { symbol: 'CAPACITE',     name: 'Capacite Infraprojects' },
  { symbol: 'CCL',          name: 'CCL Products India' },
  { symbol: 'CIGNITI',      name: 'Cigniti Technologies' },
  { symbol: 'CLEAN',        name: 'Clean Science & Technology' },
  { symbol: 'CONFIPET',     name: 'Confidence Petroleum India' },
  { symbol: 'CSBBANK',      name: 'CSB Bank' },
  { symbol: 'DATAMATICS',   name: 'Datamatics Global Services' },
  { symbol: 'DCMSHRIRAM',   name: 'DCM Shriram' },
  { symbol: 'DEEPIND',      name: 'Deep Industries' },
  { symbol: 'DFMFOODS',     name: 'DFM Foods' },
  { symbol: 'EDELWEISS',    name: 'Edelweiss Financial Services' },
  { symbol: 'EIMCO',        name: 'EIMCO Elecon' },
  { symbol: 'ELIN',         name: 'Elin Electronics' },
  { symbol: 'EQUITAS',      name: 'Equitas Holdings' },
  { symbol: 'EROSMEDIA',    name: 'Eros STX Global' },
  { symbol: 'ESABINDIA',    name: 'Esab India' },
  { symbol: 'FMGOETZE',     name: 'Federal-Mogul Goetze' },
  { symbol: 'GANDHAR',      name: 'Gandhar Oil Refinery' },
  { symbol: 'GARFIBRES',    name: 'Garware Technical Fibres' },
  { symbol: 'GATEWAY',      name: 'Gateway Distriparks' },
  { symbol: 'GHCLTEXTIL',   name: 'GHCL Textiles' },
  { symbol: 'GIPCL',        name: 'Gujarat Industries Power' },
  { symbol: 'GKWLIMITED',   name: 'GKW' },
  { symbol: 'GLOBUSSPR',    name: 'Globus Spirits' },
  { symbol: 'GMMPFAUDLR',   name: 'GMM Pfaudler' },
  { symbol: 'GPIL',         name: 'Godawari Power & Ispat' },
  { symbol: 'GREENLAM',     name: 'Greenlam Industries' },
  { symbol: 'GREENPLY',     name: 'Greenply Industries' },
  { symbol: 'GULFOILLUB',   name: 'Gulf Oil Lubricants' },
  { symbol: 'HAPPSTMNDS',   name: 'Happiest Minds Technologies' },
  { symbol: 'HERITGFOOD',   name: 'Heritage Foods' },
  { symbol: 'HINDWAREAP',   name: 'Hindware Home Innovation' },
  { symbol: 'HNDFDS',       name: 'Hindustan Foods' },
  { symbol: 'IBREALEST',    name: 'Indiabulls Real Estate' },
  { symbol: 'IDFC',         name: 'IDFC' },
  { symbol: 'IIFLSEC',      name: 'IIFL Securities' },
  { symbol: 'INDIACEM',     name: 'India Cements' },
  { symbol: 'INGERRAND',    name: 'Ingersoll Rand India' },
  { symbol: 'ISGEC',        name: 'ISGEC Heavy Engineering' },
  { symbol: 'ITDCEM',       name: 'ITD Cementation India' },
  { symbol: 'JAGSNPHARM',   name: 'Jagsonpal Pharmaceuticals' },
  { symbol: 'JBCHEPHARM',   name: 'J B Chemicals & Pharma' },
  { symbol: 'JCHEMINVEST',  name: 'JM Financial' },
  { symbol: 'JINDALSTEL',   name: 'Jindal Steel & Power' },
  { symbol: 'JKLAKSHMI',    name: 'JK Lakshmi Cement' },
  { symbol: 'JMFINANCIL',   name: 'JM Financial' },
  { symbol: 'KALPATPOWR',   name: 'Kalpataru Projects International' },
  { symbol: 'KANPRPLAS',    name: 'Kanpur Plastipack' },
  { symbol: 'KENNAMET',     name: 'Kennametal India' },
  { symbol: 'KIRLFER',      name: 'Kirloskar Ferrous Industries' },
  { symbol: 'KIRLPNU',      name: 'Kirloskar Pneumatic' },
  { symbol: 'KOTAKPSU',     name: 'Kotak PSU ETF' },
  { symbol: 'KSCL',         name: 'Kaveri Seed Company' },
  { symbol: 'LGBBROSLTD',   name: 'LG Balakrishnan & Bros' },
  { symbol: 'LLOYDSME',     name: 'Lloyds Metals & Energy' },
  { symbol: 'LPDC',         name: 'Lypsa Gems & Jewellery' },
  { symbol: 'LTFOODS',      name: 'LT Foods' },
  { symbol: 'LUXIND',       name: 'Lux Industries' },
  { symbol: 'MAHSEAMLES',   name: 'Maharashtra Seamless' },
  { symbol: 'MANALIPETC',   name: 'Manali Petrochemicals' },
  { symbol: 'MANGCHEFER',   name: 'Mangalore Chemicals & Fert' },
  { symbol: 'MASFIN',       name: 'MAS Financial Services' },
  { symbol: 'MATSYA',       name: 'Matsya Shiksha Samiti' },
  { symbol: 'MAYURUNIQ',    name: 'Mayur Uniquoters' },
  { symbol: 'MIDHANI',      name: 'Mishra Dhatu Nigam' },
  { symbol: 'MMTC',         name: 'MMTC' },
  { symbol: 'MOHNISH',      name: 'Mohnish Industries' },
  { symbol: 'MRPL',         name: 'Mangalore Refinery & Petrochem' },
  { symbol: 'MTAR',         name: 'MTAR Technologies' },
  { symbol: 'NESCAFE',      name: 'Nesca Beverages' },
  { symbol: 'NETWORK18',    name: 'Network18 Media' },
  { symbol: 'NRBBEARING',   name: 'NRB Bearing' },
  { symbol: 'NSIL',         name: 'NSIL' },
  { symbol: 'OCCL',         name: 'Oriental Carbon & Chemicals' },
  { symbol: 'OMAXE',        name: 'Omaxe' },
  { symbol: 'OPTIEMUS',     name: 'Optiemus Infracom' },
  { symbol: 'ORISSAMINE',   name: 'Orissa Minerals Development' },
  { symbol: 'PCBL',         name: 'PCBL' },
  { symbol: 'PENIND',       name: 'Peninsula Land' },
  { symbol: 'PGHH',         name: 'Procter & Gamble Health' },
  { symbol: 'PNBGILTS',     name: 'PNB Gilts' },
  { symbol: 'POLYMED',      name: 'Poly Medicure' },
  { symbol: 'POLYPLEX',     name: 'Polyplex Corporation' },
  { symbol: 'PRAKASH',      name: 'Prakash Industries' },
  { symbol: 'PREMIER',      name: 'Premier Explosives' },
  { symbol: 'PRINCEPIPE',   name: 'Prince Pipes & Fittings' },
  { symbol: 'QUESS',        name: 'Quess Corp' },
  { symbol: 'RADICO',       name: 'Radico Khaitan' },
  { symbol: 'RAJESHEXPO',   name: 'Rajesh Exports' },
  { symbol: 'RKFORGE',      name: 'RK Forgings' },
  { symbol: 'ROHLTD',       name: 'Rohit Ferro-Tech' },
  { symbol: 'ROSSARI',      name: 'Rossari Biotech' },
  { symbol: 'RTNPOWER',     name: 'Rattanindia Power' },
  { symbol: 'RUBYMILLS',    name: 'Ruby Mills' },
  { symbol: 'RUPA',         name: 'Rupa & Company' },
  { symbol: 'SAREGAMA',     name: 'Saregama India' },
  { symbol: 'SHARDACROP',   name: 'Sharda Cropchem' },
  { symbol: 'SINTERCOM',    name: 'Sintercom India' },
  { symbol: 'SKIPPER',      name: 'Skipper' },
  { symbol: 'SNOWMAN',      name: 'Snowman Logistics' },
  { symbol: 'SOLARA',       name: 'Solara Active Pharma Sciences' },
  { symbol: 'SOLARINDS',    name: 'Solar Industries India' },
  { symbol: 'SOTL',         name: 'Savita Oil Technologies' },
  { symbol: 'SPANDANA',     name: 'Spandana Sphoorty Financial' },
  { symbol: 'SPLPETRO',     name: 'SEPC' },
  { symbol: 'STOVEKRAFT',   name: 'Stovekraft' },
  { symbol: 'STYRENIX',     name: 'Styrenix Performance Materials' },
  { symbol: 'SUDARSCHEM',   name: 'Sudarshan Chemical Industries' },
  { symbol: 'SUMICHEM',     name: 'Sumitomo Chemical India' },
  { symbol: 'SUNDARMHLD',   name: 'Sundaram Finance Holdings' },
  { symbol: 'SUVEN',        name: 'Suven Pharmaceuticals' },
  { symbol: 'SUVENPHAR',    name: 'Suven Life Sciences' },
  { symbol: 'SWSOLAR',      name: 'Sterling and Wilson Renewable' },
  { symbol: 'TATAINVEST',   name: 'Tata Investment Corporation' },
  { symbol: 'TDPOWSYS',     name: 'TD Power Systems' },
  { symbol: 'TIMETECHNO',   name: 'Time Technoplast' },
  { symbol: 'TITAGARH',     name: 'Titagarh Rail Systems' },
  { symbol: 'TOTALTV',      name: 'TTML' },
  { symbol: 'TVSHLTD',      name: 'TVS Holdings' },
  { symbol: 'UCOBANK',      name: 'UCO Bank' },
  { symbol: 'UNIVPHOTO',    name: 'Uniflex Cables' },
  { symbol: 'UTIAMC',       name: 'UTI Asset Management' },
  { symbol: 'VALDEL',       name: 'Valdel Engineers & Constructors' },
  { symbol: 'VARDHACRLC',   name: 'Vardhman Acrylics' },
  { symbol: 'VIJAYA',       name: 'Vijaya Diagnostic Centre' },
  { symbol: 'VINATIORGA',   name: 'Vinati Organics' },
  { symbol: 'WEIZMANIND',   name: 'Weizmann Forex' },
  { symbol: 'XCHANGING',    name: 'Xchanging Solutions' },
  { symbol: 'YATHARTH',     name: 'Yatharth Hospital' },
  { symbol: 'ZYDUSWELL',    name: 'Zydus Wellness' },
]

// ─── Segment map ───────────────────────────────────────────────────────────────

import { NIFTY_100_STOCKS } from './stock-universe'

export type FullScanSegment = 'large' | 'mid' | 'small'

export function getSegmentStocks(segment: FullScanSegment): StockEntry[] {
  switch (segment) {
    case 'large':
      // NIFTY 100 + additional large caps (dedup by symbol)
      const seen = new Set(NIFTY_100_STOCKS.map(s => s.symbol))
      const extras = LARGE_CAP_EXTRA.filter(s => !seen.has(s.symbol))
      return [...NIFTY_100_STOCKS, ...extras]
    case 'mid':
      return MID_CAP_STOCKS
    case 'small':
      return SMALL_CAP_STOCKS
  }
}

export const SEGMENT_META: Record<FullScanSegment, { label: string; color: string; approxCount: number }> = {
  large: { label: 'Large Cap',  color: '#22C55E', approxCount: 150 },
  mid:   { label: 'Mid Cap',    color: '#F59E0B', approxCount: 90  },
  small: { label: 'Small Cap',  color: '#F97316', approxCount: 140 },
}
