/**
 * Stock Universe for Trade Finder
 * NIFTY 100 = NIFTY 50 + NIFTY Next 50
 *
 * yahooSymbol: override for symbols with special chars (e.g. M&M → M%26M.NS)
 * Default: symbol + '.NS'
 */

export interface StockEntry {
  symbol: string      // display / store symbol
  name: string
  yahooSymbol?: string  // Yahoo Finance ticker override (full, e.g. 'M%26M.NS')
}

export const NIFTY_100_STOCKS: StockEntry[] = [
  // ─── NIFTY 50 ───────────────────────────────────────────────────────────────
  { symbol: 'RELIANCE',    name: 'Reliance Industries' },
  { symbol: 'TCS',         name: 'Tata Consultancy Services' },
  { symbol: 'HDFCBANK',    name: 'HDFC Bank' },
  { symbol: 'ICICIBANK',   name: 'ICICI Bank' },
  { symbol: 'INFY',        name: 'Infosys' },
  { symbol: 'HINDUNILVR',  name: 'Hindustan Unilever' },
  { symbol: 'ITC',         name: 'ITC' },
  { symbol: 'SBIN',        name: 'State Bank of India' },
  { symbol: 'BHARTIARTL',  name: 'Bharti Airtel' },
  { symbol: 'KOTAKBANK',   name: 'Kotak Mahindra Bank' },
  { symbol: 'LT',          name: 'Larsen & Toubro' },
  { symbol: 'AXISBANK',    name: 'Axis Bank' },
  { symbol: 'BAJFINANCE',  name: 'Bajaj Finance' },
  { symbol: 'MARUTI',      name: 'Maruti Suzuki' },
  { symbol: 'ASIANPAINT',  name: 'Asian Paints' },
  { symbol: 'TATAMOTORS',  name: 'Tata Motors' },
  { symbol: 'SUNPHARMA',   name: 'Sun Pharmaceutical' },
  { symbol: 'WIPRO',       name: 'Wipro' },
  { symbol: 'HCLTECH',     name: 'HCL Technologies' },
  { symbol: 'TITAN',       name: 'Titan Company' },
  { symbol: 'ULTRACEMCO',  name: 'UltraTech Cement' },
  { symbol: 'NESTLEIND',   name: 'Nestle India' },
  { symbol: 'POWERGRID',   name: 'Power Grid Corp' },
  { symbol: 'NTPC',        name: 'NTPC' },
  { symbol: 'TATASTEEL',   name: 'Tata Steel' },
  { symbol: 'TECHM',       name: 'Tech Mahindra' },
  { symbol: 'ONGC',        name: 'Oil & Natural Gas Corp' },
  { symbol: 'ADANIENT',    name: 'Adani Enterprises' },
  { symbol: 'COALINDIA',   name: 'Coal India' },
  { symbol: 'JSWSTEEL',    name: 'JSW Steel' },
  { symbol: 'BAJAJFINSV',  name: 'Bajaj Finserv' },
  { symbol: 'BPCL',        name: 'Bharat Petroleum' },
  { symbol: 'BRITANNIA',   name: 'Britannia Industries' },
  { symbol: 'CIPLA',       name: 'Cipla' },
  { symbol: 'DIVISLAB',    name: "Divi's Laboratories" },
  { symbol: 'DRREDDY',     name: "Dr. Reddy's Laboratories" },
  { symbol: 'EICHERMOT',   name: 'Eicher Motors' },
  { symbol: 'GRASIM',      name: 'Grasim Industries' },
  { symbol: 'HDFCLIFE',    name: 'HDFC Life Insurance' },
  { symbol: 'HEROMOTOCO',  name: 'Hero MotoCorp' },
  { symbol: 'HINDALCO',    name: 'Hindalco Industries' },
  { symbol: 'INDUSINDBK',  name: 'IndusInd Bank' },
  { symbol: 'M&M',         name: 'Mahindra & Mahindra',  yahooSymbol: 'M%26M.NS' },
  { symbol: 'SBILIFE',     name: 'SBI Life Insurance' },
  { symbol: 'SHRIRAMFIN',  name: 'Shriram Finance' },
  { symbol: 'TATACONSUM',  name: 'Tata Consumer Products' },
  { symbol: 'TRENT',       name: 'Trent' },
  { symbol: 'BAJAJ-AUTO',  name: 'Bajaj Auto' },
  { symbol: 'APOLLOHOSP',  name: 'Apollo Hospitals' },
  { symbol: 'ADANIPORTS',  name: 'Adani Ports & SEZ' },

  // ─── NIFTY Next 50 ──────────────────────────────────────────────────────────
  { symbol: 'AMBUJACEM',   name: 'Ambuja Cements' },
  { symbol: 'DMART',       name: 'Avenue Supermarts' },
  { symbol: 'BANKBARODA',  name: 'Bank of Baroda' },
  { symbol: 'BEL',         name: 'Bharat Electronics' },
  { symbol: 'BHEL',        name: 'Bharat Heavy Electricals' },
  { symbol: 'CANBK',       name: 'Canara Bank' },
  { symbol: 'CHOLAFIN',    name: 'Cholamandalam Investment' },
  { symbol: 'COLPAL',      name: 'Colgate-Palmolive India' },
  { symbol: 'DABUR',       name: 'Dabur India' },
  { symbol: 'DLF',         name: 'DLF' },
  { symbol: 'GAIL',        name: 'GAIL India' },
  { symbol: 'GODREJCP',    name: 'Godrej Consumer Products' },
  { symbol: 'GODREJPROP',  name: 'Godrej Properties' },
  { symbol: 'HAVELLS',     name: 'Havells India' },
  { symbol: 'HAL',         name: 'Hindustan Aeronautics' },
  { symbol: 'ICICIPRULI',  name: 'ICICI Prudential Life' },
  { symbol: 'INDUSTOWER',  name: 'Indus Towers' },
  { symbol: 'IRFC',        name: 'Indian Railway Finance Corp' },
  { symbol: 'LTIM',        name: 'LTIMindtree' },
  { symbol: 'LUPIN',       name: 'Lupin' },
  { symbol: 'MARICO',      name: 'Marico' },
  { symbol: 'MUTHOOTFIN',  name: 'Muthoot Finance' },
  { symbol: 'NAUKRI',      name: 'Info Edge (Naukri)' },
  { symbol: 'OFSS',        name: 'Oracle Financial Services' },
  { symbol: 'PAGEIND',     name: 'Page Industries' },
  { symbol: 'PERSISTENT',  name: 'Persistent Systems' },
  { symbol: 'PIIND',       name: 'PI Industries' },
  { symbol: 'POLYCAB',     name: 'Polycab India' },
  { symbol: 'RECLTD',      name: 'REC' },
  { symbol: 'SAIL',        name: 'Steel Authority of India' },
  { symbol: 'SIEMENS',     name: 'Siemens India' },
  { symbol: 'TATAPOWER',   name: 'Tata Power' },
  { symbol: 'TORNTPHARM',  name: 'Torrent Pharmaceuticals' },
  { symbol: 'VEDL',        name: 'Vedanta' },
  { symbol: 'ZOMATO',      name: 'Zomato' },
  { symbol: 'VBL',         name: 'Varun Beverages' },
  { symbol: 'VOLTAS',      name: 'Voltas' },
  { symbol: 'BERGEPAINT',  name: 'Berger Paints India' },
  { symbol: 'OBEROIRLTY',  name: 'Oberoi Realty' },
  { symbol: 'SUNDARMFIN',  name: 'Sundaram Finance' },
  { symbol: 'TORNTPOWER',  name: 'Torrent Power' },
  { symbol: 'BOSCHLTD',    name: 'Bosch India' },
  { symbol: 'UBL',         name: 'United Breweries' },
  { symbol: 'LTTS',        name: 'L&T Technology Services' },
  { symbol: 'NYKAA',       name: 'Nykaa (FSN E-Commerce)' },
  { symbol: 'ZYDUSLIFE',   name: 'Zydus Lifesciences' },
  { symbol: 'ALKEM',       name: 'Alkem Laboratories' },
  { symbol: 'AUROPHARMA',  name: 'Aurobindo Pharma' },
  { symbol: 'IDFCFIRSTB',  name: 'IDFC First Bank' },
  { symbol: 'PNB',         name: 'Punjab National Bank' },
]
